# Generated by Django 5.2.4 on 2026-02-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainders', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remainders.category'),
        ),
    ]
