# Generated by Django 5.2.4 on 2026-02-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('remainders', '0003_remainder_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
